#include "usage.h"

void cy_print_usage(FILE* out) {
    std::fputs(
        "cyphal-reassemble — reassemble Cyphal/CAN v1.0 transfers from Arrow IPC frame streams\n"
        "\n"
        "Usage:\n"
        "  cyphal-reassemble < frames.arrows > transfers.arrows\n"
        "\n"
        "Reads an Arrow IPC stream of pre-filtered Cyphal frames from stdin and writes an\n"
        "Arrow IPC stream of reassembled transfers to stdout. Diagnostics and a summary line\n"
        "(frames_in / transfers_out / errors / oom) go to stderr.\n"
        "\n"
        "Options:\n"
        "  -h, --help    Print this help message and exit.\n"
        "\n"
        "Input schema (Arrow IPC stream):\n"
        "  Column      Type                    Required\n"
        "  timestamp   timestamp[us, UTC]      yes\n"
        "  id          uint32 (29-bit CAN ID)  yes\n"
        "  data        binary (incl. tail)     yes\n"
        "  rti         uint8                   no (default 0)\n"
        "\n"
        "Extra columns are ignored. One invocation handles one reassembly domain\n"
        "(typically one CAN channel).\n"
        "\n"
        "Output schema (Arrow IPC stream):\n"
        "  timestamp, type, id, source, dest, priority, transfer_id, payload, length\n"
        "\n"
        "  type:     \"Message\" | \"Request\" | \"Response\"\n"
        "  id:       subject-id or service-id (int16)\n"
        "  source:   origin node-id (uint8, null if anonymous)\n"
        "  dest:     destination node-id (uint8, null for messages)\n"
        "  priority: 0..7 (uint8)\n"
        "  transfer_id: 0..31 (uint8)\n"
        "  payload:  raw reassembled bytes (binary)\n"
        "  length:   payload byte count (int32)\n"
        "\n"
        "Exit status is non-zero only on fatal I/O or schema errors.\n",
        out);
}
