#include "usage.h"

void cy_print_usage(FILE* out) {
    std::fputs(
        "cyphal-reassemble — reassemble Cyphal/CAN v1.0 transfers from Arrow IPC frame streams\n"
        "\n"
        "Usage:\n"
        "  cyphal-reassemble < frames.arrows > transfers.arrows\n"
        "\n"
        "Reads an Arrow IPC stream of pre-filtered Cyphal frames from stdin and writes an\n"
        "Arrow IPC stream of reassembled transfers to stdout. Diagnostics and a summary line\n"
        "(frames_in / transfers_out / errors / oom) go to stderr.\n"
        "\n"
        "Options:\n"
        "  -h, --help    Print this help message and exit.\n"
        "\n"
        "Input schema (Arrow IPC stream):\n"
        "  Column      Type                    Required\n"
        "  timestamp   timestamp[us, UTC]      yes\n"
        "  id          uint32 (29-bit CAN ID)  yes\n"
        "  data        binary (incl. tail)     yes\n"
        "  rti         uint8                   no (default 0)\n"
        "\n"
        "Extra columns are ignored. One invocation handles one reassembly domain\n"
        "(typically one CAN channel).\n"
        "\n"
        "Output schema (Arrow IPC stream):\n"
        "  Column        Type                              Required\n"
        "  timestamp     timestamp[us, UTC]                yes\n"
        "  type          utf8 (Message|Request|Response)   yes\n"
        "  id            int16 (subject-id or service-id)  yes\n"
        "  source        uint8 (null if anonymous)         no\n"
        "  dest          uint8 (null for messages)         no\n"
        "  priority      uint8                             no\n"
        "  transfer_id   uint8                             no\n"
        "  payload       binary (raw reassembled bytes)    no\n"
        "  length        int32 (payload byte count)        no\n"
        "\n"
        "Exit status is non-zero only on fatal I/O or schema errors.\n",
        out);
}
